name: LLM
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.8.30=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py310h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py310h06a4308_0
  - ipython=8.27.0=py310h06a4308_0
  - jedi=0.19.1=py310h06a4308_0
  - jinja2=3.1.4=py310h06a4308_1
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.4=py310h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.0.0=py310hfdbf927_0
  - pip=24.2=py310h06a4308_0
  - platformdirs=3.10.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - pytorch=2.5.1=py3.10_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py310_cu118
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu118
  - tornado=6.4.2=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.3=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - absl-py==2.2.2
    - accelerate==1.2.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.10
    - aiosignal==1.3.1
    - async-timeout==5.0.1
    - attrs==24.2.0
    - bitsandbytes==0.45.0
    - click==8.1.8
    - datasets==3.2.0
    - dill==0.3.8
    - evaluate==0.4.3
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - huggingface-hub==0.26.5
    - joblib==1.4.2
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - multidict==6.1.0
    - multiprocess==0.70.16
    - nltk==3.9.1
    - packaging==24.2
    - pandas==2.2.3
    - peft==0.14.0
    - propcache==0.2.1
    - protobuf==6.30.2
    - psutil==6.1.0
    - pyarrow==18.1.0
    - pygments==2.18.0
    - pytz==2024.2
    - regex==2024.11.6
    - rich==13.9.4
    - rouge-score==0.1.2
    - safetensors==0.4.5
    - sentencepiece==0.2.0
    - six==1.17.0
    - sympy==1.13.1
    - tokenizers==0.20.3
    - tqdm==4.67.1
    - transformers==4.46.3
    - trl==0.12.2
    - tzdata==2024.2
    - xxhash==3.5.0
    - yarl==1.18.3
prefix: /home/sadia/anaconda3/envs/LLM
